name: merge main
on:
  push:
    branches: [develop]
jobs:
  Crear-Release:
    name: Crear-release
    if:  ${{ contains(github.event.head_commit.message, 'RELEASE') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v3
      - name: Crear rama
        id: crear-rama
        if: ${{ contains(github.event.head_commit.message, 'RELEASE') }}
        run: |
          git checkout -b release
          git push -f -u origin release

  merege-release-desarrollo:
    name: Merge-desarrolo
    needs: Crear-Release
    runs-on: ubuntu-latest
    steps:
    - name: Mezcla release -> develop
      uses: devmasx/merge-branch@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: develop
        target-branch: release
  

  correr-test-funcionalidad:
    name: Correr-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.7.5"
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter test
  
  merege-release-main:
    name: Merge-main
    needs: correr-test-funcionalidad
    runs-on: ubuntu-latest
    steps:
    - name: Mezcla ${{ github.ref }} -> develop
      uses: devmasx/merge-branch@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: release
        target-branch: main