name: TEST tets
run-name: ${{ github.actor }} is Deploy coverage 🚀⚗🔮🤖
on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v1
    # we need java to build android apks
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # this flutter action does the heavy lifting for us
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    # get packages as you used to in your computer
    - run: flutter pub get
    # Now build apk
    - run: flutter build apk --split-per-abi
    # now relase the just created build
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*.apk"
